apiVersion: v1
kind: Service
metadata:
  labels:
    app: weatherapp
    release: 1.0.0
  name: weatherapp
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: weatherapp
    release: 1.0.0
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
